name: Auto issue Github Token

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run deployment script
        run: |
          echo "Starting deploy..."
          # Simulando um erro
          exit 1
        id: deploy

      - name: Check deployment result
        if: failure()
        run: echo "Deployment failed!"

      - name: Create Issue on Failure
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Falha proposital identificada. Infnet."
          content-filepath: ./.github/issue-template.md
