name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/**'
  workflow_dispatch:
    inputs:
      run_lint:
        description: 'Lint'
        required: false
        default: true
        type: boolean
      run_tests:
        description: 'Test'
        required: false
        default: true
        type: boolean

jobs:
  lint-and-test:
    uses: ./.github/workflows/lint-and-test.yml
    with:
      run_lint: ${{ inputs.run_lint || true }}
      run_tests: ${{ inputs.run_tests || true }}

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs:
      - lint-and-test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Package with Maven
        run: mvn package

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
      - package
    steps:
      - name: Deploy Success Message
        run: echo "Deploy realizado com sucesso"
