name: Lint and Test

on:
  workflow_call:
    inputs:
      run_lint:
        required: false
        type: boolean
        default: true
      run_tests:
        required: false
        type: boolean
        default: true

jobs:
  lint:
    if: ${{ inputs.run_lint }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Verificação de código (lint)
        run: mvn checkstyle:check || echo " Checkstyle Failed. Continuando..."

  test:
    if: ${{ inputs.run_tests }}
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Tests
        run: mvn test