name: Test Self-Hosted Runner Tao-nuvem

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-runner:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Info do Sistema
        run: |
          echo "=== System Information ==="
          hostname-ctl
          echo ""

      - name: Check Java version (if available)
        run: |
          echo "=== Java Version ==="
          java -version || echo "Java not installed"
        continue-on-error: true

      - name: Instalando Software adicional
        run: |
          echo "=== Instalando Cowsay... ==="
            sudo apt-get update
            sudo apt-get install -y cowsay
            echo "Instalado: cowsay"
        continue-on-error: true

      - name: Testando Software Instalado
        run: |
          echo "=== Testando CowSay ==="
            cowsay "Estou instalado!!!"

      - name: Verificação do Runner
        run: |
          echo "=== Runner Verification ==="
          echo "Runner Name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Architecture: $RUNNER_ARCH"
          echo "Workflow: $GITHUB_WORKFLOW"
          echo "Repository: $GITHUB_REPOSITORY"
          echo ""